# **Data Loading**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
sns.set(style="whitegrid")

df=pd.read_csv("/home/user/DSP_Lab/Airline_Project/CSV_files/data_preprocessing.csv")
df.head()

,Record_id,id,Gender,Customer Type,Age,Age_group,Type of Travel,Class,Flight Distance,Inflight wifi service,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,1,19556,Female,Loyal Customer,52,Senior,Business travel,Eco,160,5,...,5,5,5,5,2,5,5,50,44.0,1
1,2,90035,Female,Loyal Customer,36,Mid,Business travel,Business,2863,1,...,4,4,4,4,3,4,5,0,0.0,1
2,3,12360,Male,disloyal Customer,20,Young,Business travel,Eco,192,2,...,2,4,1,3,2,2,2,0,0.0,0
3,4,77959,Male,Loyal Customer,44,Mid,Business travel,Business,3377,0,...,1,1,1,1,3,1,4,0,6.0,1
4,5,36875,Female,Loyal Customer,49,Senior,Business travel,Eco,1182,2,...,2,2,2,2,4,2,4,0,20.0,1

# **Feature and Target Variable Separation**

In [3]:
X = df.drop("Satisfaction", axis=1)  
y = df["Satisfaction"]    
X.head()

,Record_id,id,Gender,Customer Type,Age,Age_group,Type of Travel,Class,Flight Distance,Inflight wifi service,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,19556,Female,Loyal Customer,52,Senior,Business travel,Eco,160,5,...,3,5,5,5,5,2,5,5,50,44.0
1,2,90035,Female,Loyal Customer,36,Mid,Business travel,Business,2863,1,...,5,4,4,4,4,3,4,5,0,0.0
2,3,12360,Male,disloyal Customer,20,Young,Business travel,Eco,192,2,...,2,2,4,1,3,2,2,2,0,0.0
3,4,77959,Male,Loyal Customer,44,Mid,Business travel,Business,3377,0,...,4,1,1,1,1,3,1,4,0,6.0
4,5,36875,Female,Loyal Customer,49,Senior,Business travel,Eco,1182,2,...,2,2,2,2,2,4,2,4,0,20.0

> In this step, we separated the dataset into input features (X) and target variable (y). 

> We removed the “satisfaction” column from the feature set using the drop() function to avoid data leakage, ensuring that the model does not get direct access to the output variable during training.

# **Encoding Categorical Variables**

In [4]:
X = pd.get_dummies(X, drop_first=True).astype(int)
X.head()

,Record_id,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,...,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Age_group_Old,Age_group_Senior,Age_group_Teen,Age_group_Young,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus
0,1,19556,52,160,5,4,3,4,3,4,...,44,0,0,0,1,0,0,0,1,0
1,2,90035,36,2863,1,1,3,1,5,4,...,0,0,0,0,0,0,0,0,0,0
2,3,12360,20,192,2,0,2,4,2,2,...,0,1,1,0,0,0,1,0,1,0
3,4,77959,44,3377,0,0,0,2,3,4,...,6,1,0,0,0,0,0,0,0,0
4,5,36875,49,1182,2,3,4,3,4,1,...,20,0,0,0,1,0,0,0,1,0

> The get_dummies() function automatically detects categorical columns based on their data type and converts them into numerical format using one-hot encoding.

> After applying one-hot encoding, the resulting values were in boolean format (True/False). These were converted into integer format (1/0) to improve readability and ensure consistency in the dataset.

# **Splitting Data Into Training and Testing Sets**

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

> The training data is used to train the machine learning model, while the testing data is used to evaluate its performance on unseen data.

> An 80-20 split was used, where 80% of the data is used for training and 20% for testing. The random_state parameter ensures reproducibility of results.

# **Feature Scaling**

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

> Feature scaling was applied using StandardScaler to bring all features to a similar scale. 

> This helps the Logistic Regression model converge faster and improves performance. 

> The scaler was fitted on the training data and then applied to the testing data to avoid data leakage.

# **Linear Models**

# **1. Logistic Regression Model Training**

In [7]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

> ## Predictions

In [8]:
y_pred_lr = model_lr.predict(X_test)
y_pred_lr

array([0, 1, 0, ..., 1, 1, 1], shape=(5196,))

> The trained Logistic Regression model was used to predict customer satisfaction on the test dataset. 

> The output consists of binary values where 0 represents dissatisfied customers and 1 represents satisfied customers.

> ## Model Accuracy

In [9]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_lr)

0.8677829099307159

> The model shows good performance, but there is still scope for improvement using more advanced models like Random Forest, which can capture complex relationships in the data.

> ## Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_lr)

array([[2629,  316],
       [ 371, 1880]])

> The model demonstrates strong performance, but there is a slight imbalance in misclassification, particularly in identifying satisfied customers.

> ## Classification Report

In [11]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.88      0.89      0.88      2945
           1       0.86      0.84      0.85      2251

    accuracy                           0.87      5196
   macro avg       0.87      0.86      0.86      5196
weighted avg       0.87      0.87      0.87      5196

> The model shows balanced performance, but it is slightly biased towards identifying dissatisfied customers more accurately than satisfied ones.

# **2. Support vector Machines (SVM)**

> ## Creating a Model

In [12]:
from sklearn.svm import SVC
model_svm = SVC()

> ## Model Training

In [13]:
model_svm.fit(X_train, y_train)

SVC()

> ## Predictions

In [14]:
y_pred_svm = model_svm.predict(X_test)
y_pred_svm

array([0, 1, 0, ..., 1, 1, 1], shape=(5196,))

> ## Model Accuracy

In [15]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_svm)

0.9387990762124712

> Compared to Logistic Regression, the SVM model provides higher accuracy, indicating that the data contains non-linear patterns that are better captured by SVM.

> ## Confusion Matrix && Classification Report

In [16]:
confusion_matrix(y_test, y_pred_svm)

print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95      2945
           1       0.94      0.91      0.93      2251

    accuracy                           0.94      5196
   macro avg       0.94      0.94      0.94      5196
weighted avg       0.94      0.94      0.94      5196

> The SVM model shows consistent performance across both classes, with slightly better recall for dissatisfied customers, making it highly reliable for identifying unhappy customers.

# **Non-Linear Models**

# **1. K-Nearest Neighbours (KNN)**

> ## Creating a Model

In [17]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=5)

> ## Model Training

In [18]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

> ## Predictions

In [19]:
y_pred_knn = model_knn.predict(X_test)
y_pred_knn

array([0, 1, 0, ..., 1, 1, 1], shape=(5196,))

> ## Model Accuracy

In [20]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_knn)

0.905504234026174

> Although KNN provides good accuracy, SVM outperforms it, making SVM a more suitable model for this dataset.

# **2. Naive Bayes**

> ## Creating a model

In [21]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()

> ## Model Training

In [22]:
model_nb.fit(X_train, y_train)

GaussianNB()

> ## Predictions

In [23]:
y_pred_nb = model_nb.predict(X_test)
y_pred_nb

array([0, 1, 1, ..., 1, 1, 1], shape=(5196,))

> ## Model Accuracy

In [24]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_nb)

0.8314087759815243

> Compared to other models, Naive Bayes shows the lowest accuracy, indicating that it is not suitable for capturing the complex relationships present in the dataset.

# **3. Decision Tree**

> ## Creating a Model

In [25]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(random_state=42)

> ## Model Training

In [26]:
model_dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

> ## Predictions

In [27]:
y_pred_dt = model_dt.predict(X_test)
y_pred_dt

array([0, 1, 0, ..., 1, 1, 1], shape=(5196,))

> ## Model Accuracy

In [28]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_dt)

0.9276366435719784

> Although the Decision Tree model performs well, its slightly lower accuracy compared to SVM suggests that it may not generalize as effectively as more robust models.

> ## Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_dt)

array([[2750,  195],
       [ 181, 2070]])

> ## Classification Report

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      2945
           1       0.91      0.92      0.92      2251

    accuracy                           0.93      5196
   macro avg       0.93      0.93      0.93      5196
weighted avg       0.93      0.93      0.93      5196

# **4. Random Forest**

> ## Creating a Model

In [31]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(random_state=42)

> ## Model Training

In [32]:
model_rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

> ## Predictions

In [33]:
y_pred_rf = model_rf.predict(X_test)
y_pred_rf

array([0, 1, 0, ..., 1, 1, 1], shape=(5196,))

> ## Model Accuracy

In [34]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_rf)

0.9511162432640493

> ## Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_rf)

array([[2843,  102],
       [ 152, 2099]])

> ## Classification Report

In [36]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      2945
           1       0.95      0.93      0.94      2251

    accuracy                           0.95      5196
   macro avg       0.95      0.95      0.95      5196
weighted avg       0.95      0.95      0.95      5196

> Among all models, Random Forest achieved the highest accuracy of approximately 95.1%, outperforming all other models.

> Although SVM showed strong performance with 94% accuracy, Random Forest slightly outperformed it by capturing complex feature interactions and reducing overfitting through ensemble learning.

> Therefore, Random Forest is selected as the best-performing model for this dataset.

# **FINAL INSIGHTS**

> Through this project, we analyzed customer satisfaction based on various service-related features such as online boarding, inflight services, seat comfort, and more.

> By applying multiple machine learning models, we identified patterns and relationships between these features and customer satisfaction levels.

> Among all the models, Random Forest performed the best with the highest accuracy and balanced performance across both satisfied and dissatisfied customers.

> This indicates that customer satisfaction is influenced by a combination of multiple factors rather than a single feature, and ensemble models are more effective in capturing these complex relationships.

> Overall, the project demonstrates how machine learning can be used to predict customer satisfaction and help businesses identify key areas for improvement.

# **Model Testing on New Customer Data**

In [37]:
import pandas as pd

columns = X.columns
new_customer = pd.DataFrame([[0]*len(columns)], columns=columns)

new_customer['Age'] = 25
new_customer['Flight Distance'] = 1000
new_customer['Inflight wifi service'] = 3
new_customer['Departure/Arrival time convenient'] = 4
new_customer['Ease of Online booking'] = 3
new_customer['Gate location'] = 2
new_customer['Food and drink'] = 4
new_customer['Online boarding'] = 5
new_customer['Arrival Delay in Minutes'] = 10

new_customer['Gender_Male'] = 1
new_customer['Customer Type_disloyal Customer'] = 0

new_customer['Age_group_Young'] = 1

new_customer['Type of Travel_Personal Travel'] = 1

new_customer['Class_Eco'] = 1
new_customer['Class_Eco Plus'] = 0

prediction = model_rf.predict(new_customer)

probability = model_rf.predict_proba(new_customer)

print("Prediction:", prediction)
print("Probability:", probability)

Prediction: [1]
Probability: [[0.23 0.77]]

/home/user/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/home/user/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

> After building and evaluating multiple machine learning models, the final selected model (Random Forest Classifier) was tested on new unseen customer data.

> The model successfully predicted the customer satisfaction level:
- Prediction Output: 1 (Satisfied Customer)

> Additionally, the probability of prediction was also calculated:
- Probability: [0.23, 0.77]

> This indicates that the model predicts the customer is satisfied with a confidence of 77%.

> Although a warning regarding feature names was observed, it does not affect the prediction results, as the model was trained using NumPy arrays and tested using a DataFrame.

In [38]:
df.to_csv("/home/user/DSP_Lab/Airline_Project/CSV_files/data_modeling.csv", index=False)